from __future__ import annotations

from typing import Any

JSONL_SCHEMA: dict[str, Any] = {
    "$schema": "https://json-schema.org/draft/2020-12/schema",
    "title": "pcap-inspector JSONL record",
    "type": "object",
    "oneOf": [
        {
            "title": "Flow summary",
            "type": "object",
            "required": ["type", "flow", "packets", "bytes"],
            "properties": {
                "type": {"const": "flow"},
                "flow": {"type": "string"},
                "packets": {"type": "integer", "minimum": 0},
                "bytes": {"type": "integer", "minimum": 0},
                "first_ts": {"type": "number"},
                "last_ts": {"type": "number"},
            },
            "additionalProperties": True,
        },
        {
            "title": "DNS event",
            "type": "object",
            "required": ["type", "ts", "flow", "id", "qr"],
            "properties": {
                "type": {"const": "dns"},
                "ts": {"type": "number"},
                "flow": {"type": "string"},
                "id": {"type": "integer"},
                "qr": {"type": "integer"},
                "qname": {"type": ["string", "null"]},
            },
            "additionalProperties": True,
        },
        {
            "title": "HTTP request event",
            "type": "object",
            "required": ["type", "ts", "flow", "request_line"],
            "properties": {
                "type": {"const": "http"},
                "ts": {"type": "number"},
                "flow": {"type": "string"},
                "request_line": {"type": "string"},
            },
            "additionalProperties": True,
        },
        {
            "title": "HTTP response event",
            "type": "object",
            "required": ["type", "ts", "flow", "status_line"],
            "properties": {
                "type": {"const": "http"},
                "ts": {"type": "number"},
                "flow": {"type": "string"},
                "status_line": {"type": "string"},
            },
            "additionalProperties": True,
        },
        {
            "title": "TLS ClientHello event",
            "type": "object",
            "required": ["type", "ts", "flow"],
            "properties": {
                "type": {"const": "tls"},
                "ts": {"type": "number"},
                "flow": {"type": "string"},
                "sni": {"type": "string"},
                "alpn": {"type": "array", "items": {"type": "string"}},
            },
            "additionalProperties": True,
        },
    ],
    "additionalProperties": True,
}

SUMMARY_JSON_SCHEMA: dict[str, Any] = {
    "$schema": "https://json-schema.org/draft/2020-12/schema",
    "title": "pcap-inspector summary JSON",
    "type": "object",
    "required": [
        "pcap",
        "totals",
        "top_dns_qnames",
        "top_tls_sni",
        "http_methods",
        "http_status_codes",
        "top_flows_by_bytes",
    ],
    "properties": {
        "pcap": {"type": "string"},
        "totals": {
            "type": "object",
            "required": ["packets_seen", "max_packets", "ip_packets", "ip_bytes", "flows"],
            "properties": {
                "packets_seen": {"type": "integer", "minimum": 0},
                "max_packets": {"type": "integer", "minimum": 0},
                "ip_packets": {"type": "integer", "minimum": 0},
                "ip_bytes": {"type": "integer", "minimum": 0},
                "flows": {"type": "integer", "minimum": 0},
                "tcp_flows": {"type": "integer", "minimum": 0},
                "udp_flows": {"type": "integer", "minimum": 0},
                "dns_queries": {"type": "integer", "minimum": 0},
                "http_requests": {"type": "integer", "minimum": 0},
                "http_responses": {"type": "integer", "minimum": 0},
                "tls_client_hellos": {"type": "integer", "minimum": 0},
                "first_ts": {"type": ["number", "null"]},
                "last_ts": {"type": ["number", "null"]},
                "duration_s": {"type": ["number", "null"]},
                "since_ts": {"type": ["number", "null"]},
                "until_ts": {"type": ["number", "null"]},
                "hosts": {"type": ["array", "null"], "items": {"type": "string"}},
                "host_nets": {"type": ["array", "null"], "items": {"type": "string"}},
                "ports": {"type": ["array", "null"], "items": {"type": "integer", "minimum": 0}},
                "protos": {"type": ["array", "null"], "items": {"type": "string"}},
                "dns_ports": {
                    "type": ["array", "null"],
                    "items": {"type": "integer", "minimum": 0},
                },
                "tls_ports": {
                    "type": ["array", "null"],
                    "items": {"type": "integer", "minimum": 0},
                },
            },
            "additionalProperties": True,
        },
        "top_dns_qnames": {
            "type": "array",
            "items": {
                "type": "object",
                "required": ["name", "count"],
                "properties": {
                    "name": {"type": "string"},
                    "count": {"type": "integer", "minimum": 0},
                },
                "additionalProperties": True,
            },
        },
        "top_tls_sni": {
            "type": "array",
            "items": {
                "type": "object",
                "required": ["name", "count"],
                "properties": {
                    "name": {"type": "string"},
                    "count": {"type": "integer", "minimum": 0},
                },
                "additionalProperties": True,
            },
        },
        "http_methods": {
            "type": "object",
            "additionalProperties": {"type": "integer", "minimum": 0},
        },
        "http_status_codes": {
            "type": "object",
            "additionalProperties": {"type": "integer", "minimum": 0},
        },
        "top_flows_by_bytes": {
            "type": "array",
            "items": {
                "type": "object",
                "required": ["name", "count"],
                "properties": {
                    "name": {"type": "string"},
                    "count": {"type": "integer", "minimum": 0},
                },
                "additionalProperties": True,
            },
        },
    },
    "additionalProperties": True,
}

TIMELINE_JSON_SCHEMA: dict[str, Any] = {
    "$schema": "https://json-schema.org/draft/2020-12/schema",
    "title": "pcap-inspector timeline JSON",
    "type": "object",
    "required": ["pcap", "totals", "flows"],
    "properties": {
        "pcap": {"type": "string"},
        "totals": {
            "type": "object",
            "required": [
                "packets_seen",
                "max_packets",
                "ip_packets",
                "ip_bytes",
                "flows",
                "first_ts",
                "last_ts",
                "duration_s",
                "since_ts",
                "until_ts",
                "hosts",
                "host_nets",
                "ports",
                "protos",
                "normalize_flows",
                "top",
            ],
            "properties": {
                "packets_seen": {"type": "integer", "minimum": 0},
                "max_packets": {"type": "integer", "minimum": 0},
                "ip_packets": {"type": "integer", "minimum": 0},
                "ip_bytes": {"type": "integer", "minimum": 0},
                "flows": {"type": "integer", "minimum": 0},
                "first_ts": {"type": ["number", "null"]},
                "last_ts": {"type": ["number", "null"]},
                "duration_s": {"type": ["number", "null"]},
                "since_ts": {"type": ["number", "null"]},
                "until_ts": {"type": ["number", "null"]},
                "hosts": {"type": ["array", "null"], "items": {"type": "string"}},
                "host_nets": {"type": ["array", "null"], "items": {"type": "string"}},
                "ports": {"type": ["array", "null"], "items": {"type": "integer", "minimum": 0}},
                "protos": {"type": ["array", "null"], "items": {"type": "string"}},
                "dns_ports": {
                    "type": ["array", "null"],
                    "items": {"type": "integer", "minimum": 0},
                },
                "tls_ports": {
                    "type": ["array", "null"],
                    "items": {"type": "integer", "minimum": 0},
                },
                "normalize_flows": {"type": "boolean"},
                "top": {"type": "integer"},
            },
            "additionalProperties": True,
        },
        "flows": {
            "type": "array",
            "items": {
                "type": "object",
                "required": [
                    "flow",
                    "packets",
                    "bytes",
                    "first_ts",
                    "last_ts",
                    "duration_s",
                    "dns_events",
                    "http_events",
                    "tls_client_hellos",
                ],
                "properties": {
                    "flow": {"type": "string"},
                    "packets": {"type": "integer", "minimum": 0},
                    "bytes": {"type": "integer", "minimum": 0},
                    "first_ts": {"type": ["number", "null"]},
                    "last_ts": {"type": ["number", "null"]},
                    "duration_s": {"type": ["number", "null"]},
                    "dns_events": {"type": "integer", "minimum": 0},
                    "http_events": {"type": "integer", "minimum": 0},
                    "tls_client_hellos": {"type": "integer", "minimum": 0},
                    "tls_sni": {"type": ["string", "null"]},
                },
                "additionalProperties": True,
            },
        },
    },
    "additionalProperties": True,
}
